Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ExpandPathArguments:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Naming/FileName:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Naming/AccessorMethodName:
  Exclude:
    - 'lib/encrypted-field/config.rb'
Layout/LineLength:
  Max: 120
Metrics/ModuleLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
AllCops:
  Exclude:
    - 'spec/**/*_spec.rb'
